# Generated by Django 4.2 on 2023-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.PositiveBigIntegerField()),
                ('survived', models.IntegerField()),
                ('p_class', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sib_sp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('ticket', models.CharField(max_length=50)),
                ('fare', models.FloatField()),
                ('cabin', models.CharField(max_length=20)),
                ('embarked', models.CharField(max_length=2)),
            ],
        ),
    ]
