# Generated by Django 4.2 on 2023-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_age_passenger_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Cabin',
            new_name='cabin',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Embarked',
            new_name='embarked',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Fare',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Pclass',
            new_name='p_class',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='PassengerId',
            new_name='passenger_id',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='SibSp',
            new_name='sib_sp',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Survived',
            new_name='survived',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='Ticket',
            new_name='ticket',
        ),
    ]
