# Generated by Django 4.2 on 2023-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_age_passenger_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passenger_id',
        ),
    ]
